import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { GraduationCap, Sparkles, ShieldCheck } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { Button, Input, Notice } from "../components/UI";

function AuthShell({title,subtitle,children}){return <div className="grid min-h-screen lg:grid-cols-[1.05fr_.95fr] bg-[#f7f5ff]"><div className="hidden overflow-hidden bg-gradient-to-br from-violet-700 via-purple-600 to-fuchsia-500 p-12 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-2 font-black text-2xl"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-white/15"><GraduationCap/></span>Joineazy</div><div className="mt-24 max-w-lg"><p className="font-bold text-violet-200">Student collaboration platform</p><h2 className="mt-3 text-5xl font-black leading-tight">A calmer way to manage courses & assignments.</h2><p className="mt-5 text-lg leading-8 text-violet-100">Keep course work, groups and submission progress in one beautiful workspace.</p><div className="mt-8 flex flex-wrap gap-2"><span className="rounded-full bg-white/10 px-3 py-2 text-sm font-semibold"><Sparkles className="mr-1 inline" size={14}/>Responsive workspace</span><span className="rounded-full bg-white/10 px-3 py-2 text-sm font-semibold"><ShieldCheck className="mr-1 inline" size={14}/>Role-based access</span></div></div></div><p className="text-sm text-violet-200">Built for learning teams · Joineazy</p></div><div className="flex items-center justify-center p-5 sm:p-8"><div className="w-full max-w-md fade-up"><div className="mb-8 lg:hidden"><div className="flex items-center gap-2 font-black text-xl"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-600 text-white"><GraduationCap size={20}/></span>Joineazy</div></div><div className="card p-7 sm:p-8"><h1 className="text-3xl font-black tracking-tight">{title}</h1><p className="mt-1 text-slate-500">{subtitle}</p><div className="mt-7">{children}</div><p className="mt-7 text-center text-xs text-slate-400">Secure JWT-powered workspace</p></div></div></div></div>}
export function Login(){const [f,setF]=useState({email:"",password:""}),[err,setErr]=useState(""),[loading,setLoading]=useState(false),nav=useNavigate();const {login}=useAuth();const submit=async e=>{e.preventDefault();setErr("");if(!f.email||!f.password)return setErr("Please enter your email and password.");setLoading(true);try{await login(f.email,f.password);nav("/")}catch(x){setErr(x.message)}finally{setLoading(false)}};return <AuthShell title="Welcome back" subtitle="Sign in to continue to your workspace">{err&&<div className="mb-4"><Notice type="error">{err}</Notice></div>}<form onSubmit={submit} className="space-y-4"><Input label="Email" type="email" autoComplete="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/><Input label="Password" type="password" autoComplete="current-password" value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/><Button loading={loading} className="w-full">Sign in</Button></form><p className="mt-5 text-center text-sm text-slate-500">New student? <Link className="font-bold text-violet-600" to="/register">Create an account</Link></p></AuthShell>}
export function Register(){const [f,setF]=useState({name:"",email:"",password:"",confirm:""}),[err,setErr]=useState(""),[loading,setLoading]=useState(false),nav=useNavigate();const {register}=useAuth();const submit=async e=>{e.preventDefault();setErr("");if(f.name.trim().length<2)return setErr("Please enter your full name.");if(f.password.length<8)return setErr("Password must be at least 8 characters.");if(f.password!==f.confirm)return setErr("Passwords do not match.");setLoading(true);try{await register(f.name,f.email,f.password);nav("/dashboard")}catch(x){setErr(x.message)}finally{setLoading(false)}};return <AuthShell title="Create your account" subtitle="Join your course collaboration workspace">{err&&<div className="mb-4"><Notice type="error">{err}</Notice></div>}<form onSubmit={submit} className="space-y-4"><Input label="Full name" autoComplete="name" value={f.name} onChange={e=>setF({...f,name:e.target.value})} required/><Input label="Email" type="email" autoComplete="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required/><Input label="Password" type="password" autoComplete="new-password" minLength={8} value={f.password} onChange={e=>setF({...f,password:e.target.value})} required/><Input label="Confirm password" type="password" autoComplete="new-password" minLength={8} value={f.confirm} onChange={e=>setF({...f,confirm:e.target.value})} required/><Button loading={loading} className="w-full">Create account</Button></form><p className="mt-5 text-center text-sm text-slate-500">Already registered? <Link className="font-bold text-violet-600" to="/login">Sign in</Link></p></AuthShell>}
